export const COMUNAS_SANTIAGO = [
  "Santiago",
  "Santiago Centro",
  "Cerrillos",
  "Cerro Navia",
  "Conchali",
  "El Bosque",
  "Estacion Central",
  "Huechuraba",
  "Independencia",
  "La Cisterna",
  "La Florida",
  "La Granja",
  "La Pintana",
  "La Reina",
  "Las Condes",
  "Lo Barnechea",
  "Lo Espejo",
  "Lo Prado",
  "Macul",
  "Maipu",
  "Nunoa",
  "Pedro Aguirre Cerda",
  "Penalolen",
  "Providencia",
  "Pudahuel",
  "Quilicura",
  "Quinta Normal",
  "Recoleta",
  "Renca",
  "San Joaquin",
  "San Miguel",
  "San Ramon",
  "Vitacura",
];
